@startuml

package "Module" {


package "Domain" {
 component [UseCases] #AliceBlue
 component [Entities] #TECHNOLOGY
 component [OutputPorts] #AliceBlue
 component [Interactors] #TECHNOLOGY

 [Interactors] -up-> [UseCases] : impl
 [Interactors] .down.> [Entities] : use
 [Interactors] .down.> [OutputPorts] : use
}

[Controllers] ..> [UseCases] : use

[Repositories] -up-> [OutputPorts] : impl

}


@enduml
