@startuml

package "Module" {


package Aggregate {
 package "Domain" {
 component [UseCases] #AliceBlue
 component [Entities] #TECHNOLOGY
 component [OutputPorts] #AliceBlue
 component [Interactors] #TECHNOLOGY

 [Interactors] -up-> [UseCases] : impl
 [Interactors] .down.> [Entities] : use
 [Interactors] .down.> [OutputPorts] : use
}

[Controllers] ..> [UseCases] : use

package "DAL" {
[Repositories] -up-> [OutputPorts] : impl
[Repositories] .down.> [ORM Entities] : use
[Repositories] .down.> [Mappers] : use
}
}
}

queue EventBus

package "Relay" {
 [RelayService] ..> [OutboxOrm] : use
 [RelayService] ..> [EventBus] : use
 [Controllers] ..> [EventBus] : use
 [OutboxOrm] <.. [DAL] : use

 database events

 [OutboxOrm] ..> [events]

}


@enduml
