export const OFFER_TAKED_CLIENT = Symbol('OFFER_TAKED_CLIENT');
export const ORDER_VALIDATED_CLIENT = Symbol('ORDER_VALIDATED_CLIENT');
export const REPORT_VALIDATED_CLIENT = Symbol('REPORT_VALIDATED_CLIENT');
